# Generated by Django 4.1 on 2022-10-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaksin', '0008_alter_vaksin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaksin',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
