# Generated by Django 4.1 on 2022-10-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='status_checkup_type',
            field=models.CharField(blank=True, choices=[('TUNGGU', 'Masih menunggu'), ('KELUAR', 'Mengeluarkan diri'), ('PERIKSA', 'Pemeriksaan'), ('OBAT', 'Menunggu obat'), ('SELESAI', 'Selesai berobat')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='doctor',
            field=models.TextField(max_length=64),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='recommendations',
            field=models.TextField(max_length=255),
        ),
    ]
