# Generated by Django 4.1 on 2022-11-02 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0003_rename_is_paid_checkup_paid_alter_checkup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkup.staff'),
        ),
    ]
