# Generated by Django 4.1 on 2022-10-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childcare', '0003_remove_childcare_id_staff_childcare_staff_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcare',
            name='description',
            field=models.CharField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
